
  trainable:
    name: BetaTrainable
    test_model: true

    splitter:
      name: SK_KFoldSplitter
      parameters:
        n_splits: 5
        random_state: 42
        shuffle: true

    validator:
      name: SK_CrossValidate
      parameters:
        n_jobs: 4
        scoring:
          - MCC

    model:
      name: CatboostClassifier
      parameters:
        n_estimators: 4
        max_depth: 3
        allow_writing_files: false

  diagnostics:

    ConfusionMatrix:
      parameters:
        plot: true
        normalize: true
        labels:
          0: antagonist
          1: agonist

    LearningCurve:
      plot: true

    Desriptives:
      plot: true
      mean: true
      median: true
      std: true
      confidenceInterval: true

    Shaps:
      plot: true


