consumer:
  name: CB2Consumer
  chunksize: 1000

data_sources:
  - name: 'CB2_5tzy'
    metadata: 'raw data from cb2_DT dataset'
    sep: '\t'
    src: "../../data/uncompressed/raw/cb2/CB2_5tzy_all_action.csv"
    length: 'compute'
    n_length: 500
    old_length: 98799

  - name: 'CB2_6kpc'
    metadata:  'raw data from cb2_DT dataset'
    sep: '\t'
    src: "../../data/uncompressed/raw/cb2/CB2_6kpc_all_action.csv"
    length: 'compute'
    n_length: 1500
    old_length: 91064

  - name: 'CB2_6kpf'
    metadata:  'raw data from cb2_DT dataset'
    sep: '\t'
    src: "../../data/uncompressed/raw/cb2/CB2_6kpf_all_action.csv"
    length: 'compute'
    n_length: 1000
    old_length: 87141

transforms:

  clean_features:
    check_for_duplicates: true
    exceptions:
      - Action
      - Ligand_Pose
      - Ligand_Pose2
      - ID
      - CB2_CAMP
      - CB2_beta_Arrestin

  remove_features:
    filters:
      - Clash
      - Proximal
      - Ligand_Pose
      - Ligand_Pose2
      - ID

  clean_labels:
    labels:
      CB2_CAMP:
        possible_values:
          - "0"
          - "1"

        relabels:
          AGONIST: "1"
          inverse agonist: "0"
          AGONIST, inverse agonist: "0"

      CB2_beta_Arrestin:
        possible_values:
          - "0"
          - "1"

        relabels:
          AGONIST: "1"
          inverse agonist: "0"
          AGONIST, inverse agonist: "0"

  convert_dtypes:
    default: float
    columns:
      CB2_CAMP: int
      CB2_beta_Arrestin: int

  concat_datasets:
    output_name: concat-data
    keep_datasets: true

  transform_gate:
    eligible_for_processing:
      - concat-data

  change_nans:
    ignore_gate: false
    value: 0

  save_locally:
    dir_location: "../../data/uncompressed/processed"
    dir_name: "big_cb2"
    processes: 3
    partition_on_columns:
      - CB2_CAMP
      - CB2_beta_Arrestin

  terminate:
    clean_up:
      - concat-data



provider:
  name: CB2Provider
  dataset_dir: '../../data/uncompressed/processed/big_cb2/concat_data'
  processes: 5
  dtype: float
  preview_frac: 0.01
  test_size: 0.05
  classes:
    - 0
    - 1
  y_names:
    - CB2_CAMP
    - CB2_beta_Arrestin
  y_target: CB2_CAMP
  random_seed: 42
  shuffle: true
  stratify: true
  to_numpy: true
