
trainable:
  program: BetaTrainable
  name: 'catboost'
  test_model: true

  splitter:
    name: SK_RepeatedStratifiedKFold
    parameters:
      n_splits: 10
      n_repeats: 3
      random_state: 42

  validator:
    name: SK_CrossValidate
    parameters:
      n_jobs: -1
      return_train_score: true

  scorers:
    - MCC

  model:
    name: CatboostClassifier
    parameters:
       allow_writing_files: false


diagnostics:
  ConfusionMatrix:
    parameters:
      plot: true
      labels:
        0: antagonist
        1: agonist

  LearningCurve:
    plot: true

  Descriptives:
    parameters:
      compatibility: ["proc_1"]
      plot: true
      mean: true
      median: true
      std: true
      confidence_interval: true

  Shaps:
    disabled: true
    plot: true




